clear all
clc
close all

%Creates figures of nanopore rims with maximum and minimum properties
%Make sure that the folder contains the data generated by
%stable_nanopores_parallel.m

n=8;
str=string(n);
load("stable_nanopores"+str+".mat");
polys=polys_ind;
%Extraction of data from sheets
filename1="shape_factor"+str+".xlsx";
filename2="minor_axis"+str+".xlsx";
filename3="major_axis"+str+".xlsx"; 
datasf=xlsread(filename1);
datami=xlsread(filename2);
datama=xlsread(filename3);
polys_index_sf=datasf(:,1);
polys_index_mi=datami(:,1);
polys_index_ma=datama(:,1);

%Plots for shape factor
num=polys_index_sf(end);
A=polys{num};
[sf1,ma1,mi1]=min_max_plotrimedge(A,n,1);
num=polys_index_sf(1);
A=polys{num};
[sf2,ma2,mi2]=min_max_plotrimedge(A,n,2);

%Plots for minor axis
num=polys_index_mi(end);
A=polys{num};
[sf3,ma3,mi3]=min_max_plotrimedge(A,n,3);
num=polys_index_mi(1);
A=polys{num};
[sf4,ma4,mi4]=min_max_plotrimedge(A,n,4);

%Plots for major axis
num=polys_index_ma(end);
A=polys{num};
[sf5,ma5,mi5]=min_max_plotrimedge(A,n,5);
num=polys_index_ma(1);
A=polys{num};
[sf6,ma6,mi6]=min_max_plotrimedge(A,n,6);

%Creates a subplot with all the property values
figure(8);
annotation('textbox', [0.1, 0.2, 0.1, 0.1], 'String', string(n)+newline+" sf="+string(sf1)+" ma="+string(ma1)+" mi="+string(mi1)+newline+" sf="+string(sf2)+" ma="+string(ma2)+" mi="+string(mi2)+newline+" sf="+string(sf3)+" ma="+string(ma3)+" mi="+string(mi3)+newline+" sf="+string(sf4)+" ma="+string(ma4)+" mi="+string(mi4)+newline+" sf="+string(sf5)+" ma="+string(ma5)+" mi="+string(mi5)+newline+" sf="+string(sf6)+" ma="+string(ma6)+" mi="+string(mi6));
