%Creates xyz files of nanopores with maximum and minimum properties
%Make sure that the folder contains the data generated by stable_nanopores_parallel.m

clear all;
clc;
close all;
n=8;
str=string(n);
    load("stable_nanopores"+str+".mat");
    polys=polys_ind;
    for type=1:3
       xyz_num(polys,n,2,type);
       xyz_num(polys,n,1,type);
    end
